Repository colcon/colcon-ros, pull requests merged in 2018-08, with the labels that each got.

#31 refactor build and test tasks for ROS packages
  colcon_ros/package_identification/ros.py
  colcon_ros/task/__init__.py
  colcon_ros/task/ament_cmake/build.py
  colcon_ros/task/ament_cmake/test.py
  colcon_ros/task/ament_python/build.py
  colcon_ros/task/ament_python/test.py
  colcon_ros/task/catkin/build.py
  colcon_ros/task/catkin/test.py
  colcon_ros/task/cmake/build.py
  colcon_ros/task/cmake/test.py
  colcon_ros/task/ros.py
  setup.cfg
Labels: enhancement, review

#32 Add missing __init__.py
  colcon_ros/task/ament_cmake/__init__.py
  colcon_ros/task/ament_python/__init__.py
  colcon_ros/task/catkin/__init__.py
  colcon_ros/task/cmake/__init__.py
Labels: bug

#34 remove build type check
  colcon_ros/package_identification/ros.py
Labels: review

#38 support ROS Python packages using a setup.cfg file
  colcon_ros/package_identification/ros.py
  test/spell_check.words
Labels: enhancement, review
