Repository colcon/colcon-ros, pull requests merged in 2019-10, with the labels that each got.

#81 increase severity of log message for package parse errors from debug to warn
  colcon_ros/package_identification/ros.py
  debian/patches/setup.cfg.patch
  setup.cfg
  stdeb.cfg
Labels: enhancement

#85 check that no arguments are passed to the setup() function in setup.py
  colcon_ros/package_identification/ros.py
  debian/patches/setup.cfg.patch
  setup.cfg
  stdeb.cfg
Labels: bug, review

#88 fix check for installed package manifest on Windows
  colcon_ros/task/ament_python/build.py
Labels: bug, review

#82 warn about missing explicit marker installation
  colcon_ros/task/ament_python/build.py
Labels: enhancement, review
